name: bounded
description: "A minimal, framework-agnostic common kernel for Domain-Driven Design (DDD)."
version: 1.0.0
homepage:

environment:
  sdk: ^3.10.7

resolution: workspace

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0

flutter:
